ALTER TABLE trades ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS trailing_stop_pct DOUBLE PRECISION;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS peak_price DOUBLE PRECISION;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS max_exit_ts TIMESTAMPTZ;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS exit_reason TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS current_price DOUBLE PRECISION;
