ALTER TABLE signal_log ADD COLUMN IF NOT EXISTS expected_move_pct DOUBLE PRECISION;
ALTER TABLE signal_log ADD COLUMN IF NOT EXISTS expected_hold_days DOUBLE PRECISION;
ALTER TABLE signal_log ADD COLUMN IF NOT EXISTS capture_rate DOUBLE PRECISION;
ALTER TABLE signal_log ADD COLUMN IF NOT EXISTS empirical_win_rate DOUBLE PRECISION;
