// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile-nav/DesktopView.tsx": () => import("../components/mockups/mobile-nav/DesktopView.tsx"),
  "./components/mockups/mobile-nav/MobilePhone.tsx": () => import("../components/mockups/mobile-nav/MobilePhone.tsx"),
  "./components/mockups/mobile-nav/TabletView.tsx": () => import("../components/mockups/mobile-nav/TabletView.tsx"),
  "./components/mockups/dashboard-inversions/DaylightReport.tsx": () => import("../components/mockups/dashboard-inversions/DaylightReport.tsx"),
  "./components/mockups/dashboard-inversions/WarmScorecard.tsx": () => import("../components/mockups/dashboard-inversions/WarmScorecard.tsx")
};
